public class Cipmyt {
    public static void main() {
        System.out.println("auayn");
        System.out.println("wbswu");
        System.out.println("ulycm");
        System.out.println("pnovj");
        System.out.println("oylww");
        System.out.println("lmimw");
        System.out.println("mvglj");
        System.out.println("tggcx");
        System.out.println("vscod");
        System.out.println("fiouc");
        System.out.println("eijfa");
        System.out.println("qamkv");
        System.out.println("wrula");
        System.out.println("pxpsr");
        System.out.println("tcaqo");
        System.out.println("eobhl");
        System.out.println("jwcwx");
        System.out.println("eyrdy");
        System.out.println("dexwb");
        System.out.println("timfo");
        System.out.println("ahdpy");
        System.out.println("pmheg");
        System.out.println("uegcq");
        System.out.println("cdibd");
        System.out.println("cejya");
        System.out.println("clqyp");
        System.out.println("mqpes");
        System.out.println("ysnig");
        System.out.println("nbfbu");
        System.out.println("otoor");
        System.out.println("acrvw");
    }
}
